version: '3.8'

services:
  server:
    build:
      context: ./file-server
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    env_file:
      - ./file-server/.env
    volumes:
      - ./file-server/uploads:/usr/src/app/uploads
      - ./file-server/logs:/usr/src/app/logs
    networks:
      - app-network

  client:
    build:
      context: ./file-uploader
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
